var events = {
     "0": {
          "host_email" : "ed@cpp.edu",
          "event_name": "Penguins vs Florida October 14th, 2017- Danny K's Billiards Orange",
          "location" : "1096 North Main Street Orange,CA",
          "start_date" : "2017-10-14",
          "start_time": "12:00",
          "end_date" : "2017-10-15",
          "end_time": "14:00",
          "event_category" : "entertainment",
          "event_description": "Watch the defending back to back Stanley Cup champions play the Florida Panthers at Danny K's Billiards in Orange, California.",
          "tags" : "sports",
          "website_link" : "https://www.meetup.com/Orange-County-Pittsburgh-Penguins-Meetup/events/243100834/",
     },
     "1": {
          "host_email" : "bob@cpp.edu",
          "event_name": "Exclusive: Once in a lifetime dinner at Club 21 Royal at Disneyland",
          "location" : "Disneyland Park, 1313 Disneyland Dr, Anaheim, CA 92802",
          "start_date" : "2017-12-19",
          "start_time": "0854",
          "end_date" : "2017-12-19",
          "end_time": "1023",
          "event_category" : "entertainment",
          "event_description": "Fun at Disneyland.",
          "tags" : "theme park",
          "website_link" : "https://www.meetup.com/Los-Angeles-Married-Couples-and-Childfree-Meetup/events/240194049/",
     },
     "2": {
          "host_email" : "jerahmeel@gmail.com",
          "event_name": "Meetup at the Prancing Skiltaire",
          "location" : "13412 Gilbert St Riverside, CA",
          "start_date" : "2017-11-05",
          "start_time": "0854",
          "end_date" : "2017-11-06",
          "end_time": "1023",
          "event_category" : "entertainment",
          "event_description": "There's a monthly meetup at a home in Garden Grove of Anaheim CA and I think it's be a great idea if we all went, there are lots of furs there and they usually do some fun stuff.",
          "tags" : "sports",
          "website_link" : "https://www.meetup.com/iefa-Inland-Empire-Furry-Association/events/243266403/",
     },
     "3": {
          "host_email" : "iloveevents10@yahoo.com",
          "event_name": "The Real Time Lords of Orange County",
          "location" : "1169 Oak Ave Pomona, CA",
          "start_date" : "2017-10-14",
          "start_time": "12:00",
          "end_date" : "2017-10-15",
          "end_time": "14:00",
          "event_category" : "entertainment",
          "event_description": "Watch Doctor Who movie.",
          "tags" : "tech",
          "website_link" : "https://www.meetup.com/OCTimeLords/events/243919688/",
     },
     "4": {
          "host_email" : "fedex@gmail.com",
          "event_name": "Think And Grow Rich book reading and discussion",
          "location" : "20007 Door St Fountain Valley, CA",
          "start_date" : "2017-10-01",
          "start_time": "1530",
          "end_date" : "2017-10-01",
          "end_time": "1700",
          "event_category" : "education",
          "event_description": "Reading books.",
          "tags" : "books",
          "website_link" : "https://www.meetup.com/meetup-group-YCnvKpdQ/events/244020664/",
     },
};

module.exports = events;
