var events = {
     "0": {
          "created": 1504572294000,
          "id": "243100834",
          "name": "Penguins vs Florida October 14th, 2017- Danny K's Billiards Orange",
          "status": "upcoming",
          "time": 1508020200000,
          "updated": 1507179985000,
          "utc_offset": -25200000,
          "waitlist_count": 0,
          "yes_rsvp_count": 3,
          "venue": {
          "id": 25019436,
          "name": "Danny K",
          "lat": 33.805877685546875,
          "lon": -117.8675765991211,
          "repinned": true,
          "address_1": "1096 North Main Street",
          "city": "Orange",
          "country": "us",
          "localized_country_name": "USA",
          "zip": "",
          "state": "CA"
          },
          "group": {
          "created": 1504571243000,
          "name": "Orange County, California Pittsburgh Penguins Meetup",
          "id": 25775793,
          "join_mode": "open",
          "lat": 33.84000015258789,
          "lon": -117.94999694824219,
          "urlname": "Orange-County-Pittsburgh-Penguins-Meetup",
          "who": "Hockey fans",
          "localized_location": "Anaheim, CA",
          "region": "en_US"
          },
          "link": "https://www.meetup.com/Orange-County-Pittsburgh-Penguins-Meetup/events/243100834/",
          "description": "<p>Watch the defending back to back Stanley Cup champions play the Florida Panthers at Danny K's Billiards in Orange, California.</p> ",
          "how_to_find_us": "Danny K's Billiards 1096 N. Main St. Orange California 92867",
          "visibility": "public"
     },
    //  "1": {
    //       "created": 1495491646000,
    //       "fee": {
    //       "accepts": "cash",
    //       "amount": 100,
    //       "currency": "USD",
    //       "description": "per person",
    //       "label": "price",
    //       "required": false
    //       },
    //       "id": "240194049",
    //       "name": "Exclusive: Once in a lifetime dinner at Club 21 Royal at Disneyland:",
    //       "status": "upcoming",
    //       "time": 1508022000000,
    //       "rsvp_close_offset": "PT1320H",
    //       "updated": 1503268690000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 10,
    //       "venue": {
    //       "id": 16908872,
    //       "name": "Disneyland Park, 1313 Disneyland Dr, Anaheim, CA 92802",
    //       "lat": 33.81216049194336,
    //       "lon": -117.9195556640625,
    //       "repinned": false,
    //       "address_1": "Disneyland Park, 1313 Disneyland Dr, Anaheim, CA 92802",
    //       "city": "Anaheim",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "92802",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1421636167000,
    //       "name": "LA Married & Engaged Couples Childfree Group: LACC",
    //       "id": 18351622,
    //       "join_mode": "approval",
    //       "lat": 34.06999969482422,
    //       "lon": -118.37999725341797,
    //       "urlname": "Los-Angeles-Married-Couples-and-Childfree-Meetup",
    //       "who": "Professional Couples",
    //       "localized_location": "Los Angeles, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/Los-Angeles-Married-Couples-and-Childfree-Meetup/events/240194049/",
    //  },
    //  "2": {
    //       "created": 1338952105000,
    //       "id": "qftdzcywnbsb",
    //       "name": "Meetup at the Prancing Skiltaire",
    //       "status": "upcoming",
    //       "time": 1508022000000,
    //       "updated": 1338952105000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 3,
    //       "venue": {
    //       "id": 7564872,
    //       "name": "The Prancing Skiltaire",
    //       "lat": 33.7679328918457,
    //       "lon": -117.96722412109375,
    //       "repinned": false,
    //       "address_1": "13412 Gilbert  St",
    //       "city": "Garden Grove",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "92844",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1264125448000,
    //       "name": "iefa · Inland Empire Furry Association",
    //       "id": 1586656,
    //       "join_mode": "open",
    //       "lat": 33.90999984741211,
    //       "lon": -117.45999908447266,
    //       "urlname": "iefa-Inland-Empire-Furry-Association",
    //       "who": "Furries",
    //       "localized_location": "Riverside, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/iefa-Inland-Empire-Furry-Association/events/243266403/",
    //       "description": "<p>There's a monthly meetup at a home in Garden Grove of Anaheim CA and I think it's be a great idea if we all went, there are lots of furs there and they usually do some fun stuff</p> ",
    //       "visibility": "public"
    //  },
    //  "3": {
    //       "link": "https://www.meetup.com/OCTimeLords/events/243919688/",
    //       "visibility": "public_limited",
    //       "group": {
    //       "created": 1323638521000,
    //       "name": "The Real Time Lords of Orange County",
    //       "id": 2936092,
    //       "join_mode": "approval",
    //       "lat": 33.779998779296875,
    //       "lon": -117.83999633789062,
    //       "urlname": "OCTimeLords",
    //       "who": "Whovians",
    //       "localized_location": "Orange, CA",
    //       "region": "en_US"
    //       },
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 14,
    //       "time": 1508022000000,
    //       "utc_offset": -25200000,
    //       "name": "Screening: QUATERMASS (the f Doctor Who)",
    //       "id": "243919688"
    //  },
    //  "4": {
    //       "created": 1507436959000,
    //       "duration": 3600000,
    //       "id": "244020664",
    //       "name": "Think And Grow Rich book reading and discussion",
    //       "status": "upcoming",
    //       "time": 1508025600000,
    //       "updated": 1507436959000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 9,
    //       "group": {
    //       "created": 1500529618000,
    //       "name": "Personal Development  Book Club",
    //       "id": 25056916,
    //       "join_mode": "open",
    //       "lat": 33.720001220703125,
    //       "lon": -117.94000244140625,
    //       "urlname": "meetup-group-YCnvKpdQ",
    //       "who": "Members",
    //       "localized_location": "Fountain Valley, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/meetup-group-YCnvKpdQ/events/244020664/",
    //  },
    //  "5": {
    //       "created": 1507830431000,
    //       "duration": 5400000,
    //       "id": "244150031",
    //       "name": "Dinner Before The Movie",
    //       "rsvp_limit": 12,
    //       "status": "upcoming",
    //       "time": 1508026500000,
    //       "rsvp_open_offset": "PT52H15M",
    //       "rsvp_close_offset": "PT15M",
    //       "updated": 1507838830000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 5,
    //       "venue": {
    //       "id": 929850,
    //       "name": "Don Ramon's Mexican Restaurant",
    //       "lat": 33.71637725830078,
    //       "lon": -118.00660705566406,
    //       "repinned": false,
    //       "address_1": "16961 Goldenwest ",
    //       "city": "Huntington Beach",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "phone": "(714) 847-4767",
    //       "zip": "92647",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1278768260000,
    //       "name": "Huntington Beach Fun Singles 50+",
    //       "id": 1673322,
    //       "join_mode": "open",
    //       "lat": 33.720001220703125,
    //       "lon": -118,
    //       "urlname": "singles-huntingtonbeach",
    //       "who": "Very Friendly Sincere People",
    //       "localized_location": "Huntington Beach, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/singles-huntingtonbeach/events/244150031/",
    //       "description": "<p>Dinner before the Movie<br/>Good inexpensive food</p> ",
    //       "how_to_find_us": "in the bar area.",
    //       "visibility": "public"
    //  },
    //  "6": {
    //       "created": 1507447826000,
    //       "duration": 14400000,
    //       "id": "244022490",
    //       "name": "Long exposure/Night photography. Fire pit and Pics",
    //       "rsvp_limit": 20,
    //       "status": "upcoming",
    //       "time": 1508027400000,
    //       "rsvp_close_offset": "PT21H",
    //       "updated": 1507767450000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 12,
    //       "group": {
    //       "created": 1506968668000,
    //       "name": "Fun Photography and Travel",
    //       "id": 26128407,
    //       "join_mode": "approval",
    //       "lat": 33.720001220703125,
    //       "lon": -118,
    //       "urlname": "Hanahanasajinsul",
    //       "who": "Members",
    //       "localized_location": "Huntington Beach, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/Hanahanasajinsul/events/244022490/",
    //  },
    //  "7": {
    //       "link": "https://www.meetup.com/makingfriends20s/events/242581326/",
    //       "visibility": "public_limited",
    //       "group": {
    //       "created": 1444168641000,
    //       "name": "Making Friends (20's only)",
    //       "id": 19002814,
    //       "join_mode": "approval",
    //       "lat": 33.790000915527344,
    //       "lon": -117.93000030517578,
    //       "urlname": "makingfriends20s",
    //       "who": "Skittle Biscuits",
    //       "localized_location": "Garden Grove, CA",
    //       "region": "en_US"
    //       },
    //       "waitlist_count": 8,
    //       "yes_rsvp_count": 18,
    //       "duration": 7200000,
    //       "time": 1508029200000,
    //       "utc_offset": -25200000,
    //       "name": "Making Friends 2nd Year Anniversary Dinner! 21+",
    //       "id": "242581326"
    //  },
    //  "8": {
    //       "link": "https://www.meetup.com/Demo-Girls-Unite/events/243204926/",
    //       "visibility": "public_limited",
    //       "group": {
    //       "created": 1494613671000,
    //       "name": "Demo Women Unite!",
    //       "id": 23737506,
    //       "join_mode": "approval",
    //       "lat": 33.810001373291016,
    //       "lon": -117.8499984741211,
    //       "urlname": "Demo-Girls-Unite",
    //       "who": "DemoPower!",
    //       "localized_location": "Orange, CA",
    //       "region": "en_US"
    //       },
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 3,
    //       "time": 1508029200000,
    //       "utc_offset": -25200000,
    //       "name": "Dinner/Drinks, Current movie or dancing @ The Ranch!",
    //       "id": "243204926"
    //  },
    //  "9": {
    //       "created": 1481432790000,
    //       "id": "whhqsnywnbsb",
    //       "name": "Greath - Age of the Undeath",
    //       "rsvp_limit": 7,
    //       "status": "upcoming",
    //       "time": 1508029200000,
    //       "rsvp_close_offset": "PT119H",
    //       "updated": 1507561419000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 7,
    //       "venue": {
    //       "id": 23526381,
    //       "name": "Rich's Gaming Garage",
    //       "lat": 33.722267150878906,
    //       "lon": -118.00104522705078,
    //       "repinned": false,
    //       "address_1": "Send message to Rich C for address",
    //       "city": "Huntington Beach",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "92647",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1409847735000,
    //       "name": "HB Weekend Gaming",
    //       "id": 16793672,
    //       "join_mode": "approval",
    //       "lat": 33.720001220703125,
    //       "lon": -118,
    //       "urlname": "HB_Weekend_Gaming",
    //       "who": "Adventurers",
    //       "localized_location": "Huntington Beach, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/HB_Weekend_Gaming/events/243244554/",
    //       "visibility": "public"
    //  },
    //  "10": {
    //       "created": 1507440195000,
    //       "duration": 3600000,
    //       "id": "244021315",
    //       "name": "✅Speed Networking✅",
    //       "status": "upcoming",
    //       "time": 1508029200000,
    //       "updated": 1507440195000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 4,
    //       "group": {
    //       "created": 1493401147000,
    //       "name": "Business Supporting Business - Networking Parties",
    //       "id": 23471769,
    //       "join_mode": "open",
    //       "lat": 33.720001220703125,
    //       "lon": -117.94000244140625,
    //       "urlname": "Business-Supporting-Business-Networking-Parties",
    //       "who": "Networkers!",
    //       "localized_location": "Fountain Valley, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/Business-Supporting-Business-Networking-Parties/events/244021315/",
    //       "description": "<p>BRING your Business Cards &amp; a smile!<br/>Come meet other local entrepreneurs✅<br/>Find new business partners, clients &amp; make new friends! ❤️</p> <p>$10(fee for regulars) $5(first timers)<br/>Fee includes snacks🌟</p> <p>A little about me, I am a mind-body transformation, I teach people how to get in the best shape of their lives and tap into the BADASS child-like Version of themselves! I love doing business with local entrepreneurs and I LOVE SUPPORTING people:) 💁🏽</p> ",
    //       "visibility": "public"
    //  },
    //  "11": {
    //       "link": "https://www.meetup.com/OC-Couples-40s-50s-AND-60s/events/242883192/",
    //       "visibility": "public_limited",
    //       "group": {
    //       "created": 1384214209000,
    //       "name": "OC Couples (40's, 50's, and 60's)",
    //       "id": 11066142,
    //       "join_mode": "approval",
    //       "lat": 33.869998931884766,
    //       "lon": -117.8499984741211,
    //       "urlname": "OC-Couples-40s-50s-AND-60s",
    //       "who": "OC Couples",
    //       "localized_location": "Placentia, CA",
    //       "region": "en_US"
    //       },
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 8,
    //       "time": 1508031000000,
    //       "utc_offset": -25200000,
    //       "name": "Sgt. Peppers Dueling Pianos in Long Beach",
    //       "id": "242883192"
    //  },
    //  "16": {
    //       "created": 1506817225000,
    //       "id": "243813369",
    //       "name": "Singles Dance Garden Grove Elks,OC's Largest Dance Floor, Sat.Oct. 14, 7p-11:30",
    //       "rsvp_limit": 300,
    //       "status": "upcoming",
    //       "time": 1508032800000,
    //       "updated": 1506900090000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 143,
    //       "venue": {
    //       "id": 21080252,
    //       "name": "Garden Grove Elks Lodge",
    //       "lat": 33.76753234863281,
    //       "lon": -117.92789459228516,
    //       "repinned": false,
    //       "address_1": "11551 Trask Ave",
    //       "city": "Garden Grove",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1352755430000,
    //       "name": "Singles in South Orange County Dance Parties & Travel",
    //       "id": 5817182,
    //       "join_mode": "open",
    //       "lat": 33.470001220703125,
    //       "lon": -117.69999694824219,
    //       "urlname": "Singles-in-South-Orange-County",
    //       "who": "Singles who Love Music & Dancing",
    //       "localized_location": "Dana Point, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/Singles-in-South-Orange-County/events/243813369/",
    //       "description": "<p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/8/600_464833128.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/f/600_464833135.jpeg" /></p> <p><b>Come early for great Seat, The +90  sign is because We are inviting all of So Cal and you with newspaper ads in OC Reg and LA Times, and dozens of Meetups and Singles Groups.</b></p> <p><b>Send this email to your friends; Tell you will be going to Garden Grove this Sat. It is open to everyone, no membership required! Time to meet some new friends in the huge ballroom! No RSVP needed, just pay at the door. Only $10 admission. </b></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Attending a party alone? Most of the ladies who attend, do attend alone. All of our Parties are in classy safe venues. We rent out the entire room, it is just our singles groups so it is easy to meet people. </b></p> <p><b><img src="https://secure.meetupstatic.com/photos/event/3/3/6/e/600_464833166.jpeg" /></b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/7/5/600_464833173.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/b/d/600_464833245.jpeg" /></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/2/7/c/600_464952924.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/e/1/7/600_463743607.jpeg" /></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><b>Now “FREE DANCE LESSONS” w/ Sherri during the cruise on Best Priced Meetup Weekend Carnival Cruise, And Now Only Wkend Cruise w/ Free Dance Lessons. </b></p> <p><b>What a Great way to Meet New Singles! </b></p> <p><b>This is the Best Price of any Singles Group on Carnival in So Cal !!!</b></p> <p><b>Interior per person double: $239 plus $120 taxes and fees (total: $359),  $558 Single private interior cabin.</b></p> <p><b>Ocean View per person double: $269 plus $120 taxes &amp; Fees (total: $389),  $658 Single private ocean view cabin.</b></p> <p><b>This Cruise is sold on over 40 Meetups nationwide. The  cabins will go up in price &amp; will be Sold Out, so hurry and reserve by calling our travel agent; Brigette Teague,[masked] ext 301, </b><a href="mailto:[masked]"><b>[masked]</b></a>.</p> <p><b>Please fill out reservation form NOW. </b></p> <p><b>​</b><b>Please make sure you check "I am not a robot" box in the lower left side of the form before submitting.​</b></p> <p><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204"><b><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204" class="linkified">http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204</a></b></a></p> <p>Champagne Cruise Schedule</p> <p>Fri. Dec. 1  Los Angeles (Long Beach), CA  Depart  4pm </p> <p>Sat. Dec. 2  Ensenada, Mexico  09:00 AM – 4pm</p> <p>Sun. Dec. 3  Fun Day At Sea </p> <p>Mon. Dec. 4  Los Angeles (Long Beach), CA, 8:00 AM  Disembark</p> ",
    //       "visibility": "public"
    //  },
    //  "17": {
    //       "created": 1506821458000,
    //       "id": "243815406",
    //       "name": "Singles Dance Garden Grove Elks,OC's Largest Dance Floor, Sat.Oct. 14, 7p-11:30",
    //       "rsvp_limit": 300,
    //       "status": "upcoming",
    //       "time": 1508032800000,
    //       "updated": 1506900054000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 112,
    //       "venue": {
    //       "id": 21080252,
    //       "name": "Garden Grove Elks Lodge",
    //       "lat": 33.76753234863281,
    //       "lon": -117.92789459228516,
    //       "repinned": false,
    //       "address_1": "11551 Trask Ave",
    //       "city": "Garden Grove",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1192685657000,
    //       "name": "Singles Dances & Singles Travel in Newport Beach",
    //       "id": 760005,
    //       "join_mode": "open",
    //       "lat": 33.630001068115234,
    //       "lon": -117.87000274658203,
    //       "urlname": "SinglesDancesNewportBeach",
    //       "who": "Single Business professionals",
    //       "localized_location": "Newport Beach, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/SinglesDancesNewportBeach/events/243815406/",
    //       "description": "<p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/8/600_464833128.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/f/600_464833135.jpeg" /></p> <p><b>Come early for great Seat, The +90  sign is because We are inviting all of So Cal and you with newspaper ads in OC Reg and LA Times, and dozens of Meetups and Singles Groups.</b></p> <p><b>Send this email to your friends; Tell you will be going to Garden Grove this Sat. It is open to everyone, no membership required! Time to meet some new friends in the huge ballroom! No RSVP needed, just pay at the door. Only $10 admission. </b></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Attending a party alone? Most of the ladies who attend, do attend alone. All of our Parties are in classy safe venues. We rent out the entire room, it is just our singles groups so it is easy to meet people. </b></p> <p><b><img src="https://secure.meetupstatic.com/photos/event/3/3/6/e/600_464833166.jpeg" /></b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/7/5/600_464833173.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/b/d/600_464833245.jpeg" /></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/2/7/c/600_464952924.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/e/1/7/600_463743607.jpeg" /></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><b>Now “FREE DANCE LESSONS” w/ Sherri during the cruise on Best Priced Meetup Weekend Carnival Cruise, And Now Only Wkend Cruise w/ Free Dance Lessons. </b></p> <p><b>What a Great way to Meet New Singles! </b></p> <p><b>This is the Best Price of any Singles Group on Carnival in So Cal !!!</b></p> <p><b>Interior per person double: $239 plus $120 taxes and fees (total: $359),  $558 Single private interior cabin.</b></p> <p><b>Ocean View per person double: $269 plus $120 taxes &amp; Fees (total: $389),  $658 Single private ocean view cabin.</b></p> <p><b>This Cruise is sold on over 40 Meetups nationwide. The  cabins will go up in price &amp; will be Sold Out, so hurry and reserve by calling our travel agent; Brigette Teague,[masked] ext 301, </b><a href="mailto:[masked]"><b>[masked]</b></a>.</p> <p><b>Please fill out reservation form NOW. </b></p> <p><b>​</b><b>Please make sure you check "I am not a robot" box in the lower left side of the form before submitting.​</b></p> <p><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204"><b><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204" class="linkified">http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204</a></b></a></p> <p>Champagne Cruise Schedule</p> <p>Fri. Dec. 1  Los Angeles (Long Beach), CA  Depart  4pm </p> <p>Sat. Dec. 2  Ensenada, Mexico  09:00 AM – 4pm</p> <p>Sun. Dec. 3  Fun Day At Sea </p> <p>Mon. Dec. 4  Los Angeles (Long Beach), CA, 8:00 AM  Disembark</p> ",
    //       "visibility": "public"
    //  },
    //  "18": {
    //       "created": 1506899202000,
    //       "id": "243838046",
    //       "name": "Singles Dance Garden Grove Elks,OC's Largest Dance Floor, Sat.Oct. 14, 7p-11:30",
    //       "rsvp_limit": 300,
    //       "status": "upcoming",
    //       "time": 1508032800000,
    //       "updated": 1506899729000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 142,
    //       "venue": {
    //       "id": 24665717,
    //       "name": "Elks Garden Grove",
    //       "lat": 33.767459869384766,
    //       "lon": -117.92800903320312,
    //       "repinned": false,
    //       "address_1": "11551 Trask Av",
    //       "city": "Garden Grove",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1455001713000,
    //       "name": "Fullerton Singles Dance Parties & I LUV to Travel",
    //       "id": 19543324,
    //       "join_mode": "open",
    //       "lat": 33.88999938964844,
    //       "lon": -117.88999938964844,
    //       "urlname": "FoxSinglesDanceParties",
    //       "who": "Fox Singles Dance Parties",
    //       "localized_location": "Fullerton, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/FoxSinglesDanceParties/events/243838046/",
    //       "description": "<p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/8/600_464833128.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/f/600_464833135.jpeg" /></p> <p><b>Come early for great Seat, The +90  sign is because We are inviting all of So Cal and you with Radio ads on KOST, newspaper ads in OC Reg and LA Times, and dozens of Meetups and Singles Groups.</b></p> <p><b>Send this email to your friends; Tell you will be going to Garden Grove this Sat. It is open to everyone, no membership required! Time to meet some new friends in the huge ballroom! No RSVP needed, just pay at the door. Only $10 admission. </b></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Attending a party alone? Most of the ladies who attend, do attend alone. All of our Parties are in classy safe venues. We rent out the entire room, it is just our singles groups so it is easy to meet people. </b></p> <p><b><img src="https://secure.meetupstatic.com/photos/event/3/3/6/e/600_464833166.jpeg" /></b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/7/5/600_464833173.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/b/d/600_464833245.jpeg" /></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/2/7/c/600_464952924.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/e/1/7/600_463743607.jpeg" /></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><b>Now “FREE DANCE LESSONS” w/ Sherri during the cruise on Best Priced Meetup Weekend Carnival Cruise, And Now Only Wkend Cruise w/ Free Dance Lessons. </b></p> <p><b>What a Great way to Meet New Singles! </b></p> <p><b>This is the Best Price of any Singles Group on Carnival in So Cal !!!</b></p> <p><b>Interior per person double: $239 plus $120 taxes and fees (total: $359),  $558 Single private interior cabin.</b></p> <p><b>Ocean View per person double: $269 plus $120 taxes &amp; Fees (total: $389),  $658 Single private ocean view cabin.</b></p> <p><b>This Cruise is sold on over 40 Meetups nationwide. The  cabins will go up in price &amp; will be Sold Out, so hurry and reserve by calling our travel agent; Brigette Teague,[masked] ext 301, </b><a href="mailto:[masked]"><b>[masked]</b></a>.</p> <p><b>Please fill out reservation form NOW. </b></p> <p><b>​</b><b>Please make sure you check "I am not a robot" box in the lower left side of the form before submitting.​</b></p> <p><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204"><b><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204" class="linkified">http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204</a></b></a></p> <p>Champagne Cruise Schedule</p> <p>Fri. Dec. 1  Los Angeles (Long Beach), CA  Depart  4pm </p> <p>Sat. Dec. 2  Ensenada, Mexico  09:00 AM – 4pm</p> <p>Sun. Dec. 3  Fun Day At Sea </p> <p>Mon. Dec. 4  Los Angeles (Long Beach), CA, 8:00 AM  Disembark</p> ",
    //       "visibility": "public"
    //  },
    //  "19": {
    //       "created": 1506899392000,
    //       "id": "243838083",
    //       "name": "Singles Dance Garden Grove Elks,OC's Largest Dance Floor, Sat.Oct. 14, 7p-11:30",
    //       "rsvp_limit": 300,
    //       "status": "upcoming",
    //       "time": 1508032800000,
    //       "updated": 1506899793000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 136,
    //       "venue": {
    //       "id": 24147341,
    //       "name": "Garden Grove Elks Lodge ",
    //       "lat": 33.76627731323242,
    //       "lon": -117.98314666748047,
    //       "repinned": false,
    //       "address_1": "11551 Trask Ave, Garden Grove, CA (map) ",
    //       "city": "Garden Grove  , Ca",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1365460955000,
    //       "name": ""There is a Party in the Valley" Singles",
    //       "id": 7979552,
    //       "join_mode": "open",
    //       "lat": 34.150001525878906,
    //       "lon": -118.44000244140625,
    //       "urlname": "There-is-a-Party-in-the-Valley-Singles",
    //       "who": "Valley Singles",
    //       "localized_location": "Sherman Oaks, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/There-is-a-Party-in-the-Valley-Singles/events/243838083/",
    //       "description": "<p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/8/600_464833128.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/f/600_464833135.jpeg" /></p> <p><b>Come early for great Seat, The +90  sign is because We are inviting all of So Cal and you with Radio ads on KOST, newspaper ads in OC Reg and LA Times, and dozens of Meetups and Singles Groups.</b></p> <p><b>Send this email to your friends; Tell you will be going to Garden Grove this Sat. It is open to everyone, no membership required! Time to meet some new friends in the huge ballroom! No RSVP needed, just pay at the door. Only $10 admission. </b></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Attending a party alone? Most of the ladies who attend, do attend alone. All of our Parties are in classy safe venues. We rent out the entire room, it is just our singles groups so it is easy to meet people. </b></p> <p><b><img src="https://secure.meetupstatic.com/photos/event/3/3/6/e/600_464833166.jpeg" /></b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/7/5/600_464833173.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/b/d/600_464833245.jpeg" /></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/2/7/c/600_464952924.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/e/1/7/600_463743607.jpeg" /></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><b>Now “FREE DANCE LESSONS” w/ Sherri during the cruise on Best Priced Meetup Weekend Carnival Cruise, And Now Only Wkend Cruise w/ Free Dance Lessons. </b></p> <p><b>What a Great way to Meet New Singles! </b></p> <p><b>This is the Best Price of any Singles Group on Carnival in So Cal !!!</b></p> <p><b>Interior per person double: $239 plus $120 taxes and fees (total: $359),  $558 Single private interior cabin.</b></p> <p><b>Ocean View per person double: $269 plus $120 taxes &amp; Fees (total: $389),  $658 Single private ocean view cabin.</b></p> <p><b>This Cruise is sold on over 40 Meetups nationwide. The  cabins will go up in price &amp; will be Sold Out, so hurry and reserve by calling our travel agent; Brigette Teague,[masked] ext 301, </b><a href="mailto:[masked]"><b>[masked]</b></a>.</p> <p><b>Please fill out reservation form NOW. </b></p> <p><b>​</b><b>Please make sure you check "I am not a robot" box in the lower left side of the form before submitting.​</b></p> <p><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204"><b><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204" class="linkified">http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204</a></b></a></p> <p>Champagne Cruise Schedule</p> <p>Fri. Dec. 1  Los Angeles (Long Beach), CA  Depart  4pm </p> <p>Sat. Dec. 2  Ensenada, Mexico  09:00 AM – 4pm</p> <p>Sun. Dec. 3  Fun Day At Sea </p> <p>Mon. Dec. 4  Los Angeles (Long Beach), CA, 8:00 AM  Disembark</p> ",
    //       "visibility": "public"
    //  },
    //  "20": {
    //       "created": 1506899504000,
    //       "id": "243838118",
    //       "name": "Singles Dance Garden Grove Elks,OC's Largest Dance Floor, Sat.Oct. 14, 7p-11:30",
    //       "rsvp_limit": 300,
    //       "status": "upcoming",
    //       "time": 1508032800000,
    //       "updated": 1506899654000,
    //       "utc_offset": -25200000,
    //       "waitlist_count": 0,
    //       "yes_rsvp_count": 143,
    //       "venue": {
    //       "id": 24665717,
    //       "name": "Elks Garden Grove",
    //       "lat": 33.767459869384766,
    //       "lon": -117.92800903320312,
    //       "repinned": false,
    //       "address_1": "11551 Trask Av",
    //       "city": "Garden Grove",
    //       "country": "us",
    //       "localized_country_name": "USA",
    //       "zip": "",
    //       "state": "CA"
    //       },
    //       "group": {
    //       "created": 1413933830000,
    //       "name": "LA & OC Counties Dancing & Much More",
    //       "id": 17778802,
    //       "join_mode": "open",
    //       "lat": 33.869998931884766,
    //       "lon": -118.05000305175781,
    //       "urlname": "LA-OC-Counties-Dancing-Much-More",
    //       "who": "SoCal Dancers & Others",
    //       "localized_location": "Cerritos, CA",
    //       "region": "en_US"
    //       },
    //       "link": "https://www.meetup.com/LA-OC-Counties-Dancing-Much-More/events/243838118/",
    //       "description": "<p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/8/600_464833128.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/4/f/600_464833135.jpeg" /></p> <p><b>Come early for great Seat, The +90  sign is because We are inviting all of So Cal and you with Radio ads on KOST, newspaper ads in OC Reg and LA Times, and dozens of Meetups and Singles Groups.</b></p> <p><b>Send this email to your friends; Tell you will be going to Garden Grove this Sat. It is open to everyone, no membership required! Time to meet some new friends in the huge ballroom! No RSVP needed, just pay at the door. Only $10 admission. </b></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Attending a party alone? Most of the ladies who attend, do attend alone. All of our Parties are in classy safe venues. We rent out the entire room, it is just our singles groups so it is easy to meet people. </b></p> <p><b><img src="https://secure.meetupstatic.com/photos/event/3/3/6/e/600_464833166.jpeg" /></b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/7/5/600_464833173.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/3/b/d/600_464833245.jpeg" /></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><img src="https://secure.meetupstatic.com/photos/event/3/2/7/c/600_464952924.jpeg" /></p> <p><img src="https://secure.meetupstatic.com/photos/event/e/1/7/600_463743607.jpeg" /></p> <p><b>&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;</b></p> <p><b>Only a Few Weeks to book Your Weekend Party Cruise on Carnival before the Rates go up or the cruise sells out !!</b></p> <p><b>Now “FREE DANCE LESSONS” w/ Sherri during the cruise on Best Priced Meetup Weekend Carnival Cruise, And Now Only Wkend Cruise w/ Free Dance Lessons. </b></p> <p><b>What a Great way to Meet New Singles! </b></p> <p><b>This is the Best Price of any Singles Group on Carnival in So Cal !!!</b></p> <p><b>Interior per person double: $239 plus $120 taxes and fees (total: $359),  $558 Single private interior cabin.</b></p> <p><b>Ocean View per person double: $269 plus $120 taxes &amp; Fees (total: $389),  $658 Single private ocean view cabin.</b></p> <p><b>This Cruise is sold on over 40 Meetups nationwide. The  cabins will go up in price &amp; will be Sold Out, so hurry and reserve by calling our travel agent; Brigette Teague,[masked] ext 301, </b><a href="mailto:[masked]"><b>[masked]</b></a>.</p> <p><b>Please fill out reservation form NOW. </b></p> <p><b>​</b><b>Please make sure you check "I am not a robot" box in the lower left side of the form before submitting.​</b></p> <p><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204"><b><a href="http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204" class="linkified">http://www.singlescruisesbymarsky.com/reserve.php?event=20171201-20171204</a></b></a></p> <p>Champagne Cruise Schedule</p> <p>Fri. Dec. 1  Los Angeles (Long Beach), CA  Depart  4pm </p> <p>Sat. Dec. 2  Ensenada, Mexico  09:00 AM – 4pm</p> <p>Sun. Dec. 3  Fun Day At Sea </p> <p>Mon. Dec. 4  Los Angeles (Long Beach), CA, 8:00 AM  Disembark</p> ",
    //       "visibility": "public"
    //  }
};
// var events = {
//
// };

module.exports = events;
